spring:
  profiles.include:
    - secret
  security:
    oauth2:
      client: # client -> 네이버, 카카오 등..
        registration:
          naver: # 이 이름과 localhost:8080/oauth2/authorization/'naver' 일치 (정해져있음)
            clientId: A8sKdDUmlEtqEuVBR1Ka
            redirectUri: http://localhost:8080/login/oauth2/code/naver # provider 안의 내용을 이곳으로 넘김
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Naver

        provider:
          naver: # 이 이름이 있어야 사용할 수 있음
            authorizationUri: https://nid.naver.com/oauth2.0/authorize # 인가_소셜(네이버) 쪽에서 계정 로그인 진행하는 화면
            tokenUri: https://nid.naver.com/oauth2.0/token # 네이버 로그인이 되면 그 응답으로 토큰 발행
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response # kakao -> id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://memorious-db.crstfhvl8zsl.ap-northeast-2.rds.amazonaws.com:3306/memorious
    username: rootMaster

mybatis:
  mapper-locations:
    - /mappers/*.xml