spring:
  profiles.include:
    - secret
  security:
    oauth2:
      client: # client -> 네이버, 카카오 등..
        registration:
          kakao:
            clientId: 9b8d585e48ccfcc2fca696e8b4fcf1a3
            redirectUri: http://localhost:8080/login/oauth2/code/kakao
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Kakao
          naver:
            clientId: A8sKdDUmlEtqEuVBR1Ka
            redirectUri: http://localhost:8080/login/oauth2/code/naver # (2) provider 안의 내용을 다시 우리쪽으로 넘김
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST
            clientName: Naver

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize # (1)인가 -소셜(네이버) 쪽에서 계정 로그인 진행하는 화면
            tokenUri: https://nid.naver.com/oauth2.0/token # 네이버 로그인이 되면 그 응답으로 토큰 발행
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response # kakao -> id

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://memorious-db.crstfhvl8zsl.ap-northeast-2.rds.amazonaws.com:3306/memorious
    username: rootMaster

mybatis:
  mapper-locations:
    - /mappers/*.xml